{{ if .Values.flowmanager.https.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-httpskeystore
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.https.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.https.localFile | b64enc }}
{{ end }}

{{ if .Values.flowmanager.db.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-db
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.db.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.db.localFile | b64enc }}
{{ end }}

{{ if .Values.flowmanager.business.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-business
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.business.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.business.localFile | b64enc }}
{{ end }}

{{ if .Values.flowmanager.governance.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-governance
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.governance.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.governance.localFile | b64enc }}
{{ end }}

{{ if .Values.flowmanager.sentinel.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-sentinel
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.sentinel.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.sentinel.localFile | b64enc }}
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-apicpubkey
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if .Values.flowmanager.apicCatalog.publicKey.createSecretFile }}
  {{ .Values.flowmanager.apicCatalog.publicKey.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.apicPublicKey.localFile | b64enc }}
{{ else }}
  catalog-public-key.pem : |-
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwOFVXV1BFVnNaVTl4WU1MQjY1YwpGc0tNUTc3bmliTTR5YnNYcUdxVm5WbmVHMW5IMWxBcWVFaG5IKy9EN0xZNXpsUWVWak11UUE3RXpua1p2ZkN6Ckx4U1V0ZVl2QU9Kb0V1NTJBblNaZ1ZXazZiL2JGaHVjRkJiOEo4bEtENE9Uc1YzcVRYVHhleEJOQ2FHZ1RRMkwKQ2xsMTBRQS96VWpwbWNtSVNPd0hpT0lWL3lBajF6am4xd2xMd3lNbWxpcUk4czV5QlQ0OGRNZ1Ixby9raHVkZQpQUTFOSjNjSUNRRGhoeVJLWGg4QlZzMzdEaXpOWjFBeHdVYXlZSWNMekx4QUIveDdGV3RiRVpUOEMwNk9IOHAyCi9YOWV3cGVSb1A1SWhsZzdCdnJaWTlPcDdDeHpPYndubXZVd2dJU3VVVHVsQzUrTXFLMGFrTWd3S21nK204czcKZ1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-apicprivkey
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if .Values.flowmanager.apicCatalog.privateKey.createSecretFile }}
  {{ .Values.flowmanager.apicCatalog.privateKey.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.apicPrivateKey.localFile | b64enc }}
{{ else }}
  catalog-private-key.pem : |-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRENmT1l1Q282WExmdGwKSG80c2IzVnVHZDhteWkrSDkxUWJWcU1kR01nQnk5dGFtMks4cWRzRnlxUmk4NFlURnJDWmVuWDVjcXRHcEhDSQpLRHN6TkZqa29GdzREOVhQUExaTHdORXFvdU5wbm5nQXFoYVZkN1hqaWoxcEhra1ZXamY4bVFjOHhwTWE4VmJkCkNvQ1h0SVYvcWdpK1hsdVlCZkJmV0QrTWpzQkdhZldPUXRWN01RZkp3RHhONytybFhKRUNPeXhsak9GK0QzM2YKNW45Z1lWbkZCaVZrZ2laK3NZMHFqNks1eXRZUXZVRkd4SVRhclN5emhXS3NoakMrMGVnTGVrek9abzhMZERqcgpBcnRjTFJ5aStJVS9DZjBwRGZSY2Nzb05SRUVka2VKdGtPUVJUdVNObEw2QlRvYjIwSERwN2RSeHlQdHpLVTRPCmxnUlpuZ0ZOQWdNQkFBRUNnZ0VBUGg0dVZwNUFsTUMyL3NFWG45R3ByQlRQVlZCV2hoTFU1alp4dXFWam5FOUUKTEZoYzNPMVRhekloOXdqWTFkZjFaOC9aUm1iOWxYNklBclQyMDQvd3BIVWpmelJ2a2RWT1ZEdXRrdlNidGV4TApYOHJ6azZHOGtvUmd3T1pQYVdaN1kwNXRKVmczTysvQlVyQThDamc2TzJCUGtwNEltekdxYUltRElwMmxnOWRjClpoYmJCVm41T1EwKzRENFRubjMwU2dkMVpySjNVQXVpd0E1eE80VWdxWjdxUkdEUUlLTFhXM0hJQ0czcUtEdUEKb1RiN0ptSUptRHl2M2U5SFFVaFFlOUpydjh1QVdLazNJdGxQMnlRVWZSTFFjVGE0bnBXTGcxT2k4RFRGT3BkKworWWNWcUJwUkNIYXlnakNHc0NDd2ZqV3RKS3RrUmM3WHl4U3JoZitSQVFLQmdRRDcwVVZzWjdPc0RvY0o1RFZiCk1udTBlVnNyTGJNQk1Vb24wMHFLMG5tU3lOemxqSjNzYlZpbnd3ckVKbHJTZnVrdGNkdTZJMm1KY3RXcHJFREkKektSYWs1V0FoY0FoZWJPTDFNYjlCMXgzQ0ZEby9mN3FyRzlUby9PQXVyd2grRFFNZVlIekw5WWtkZFY1OXQ5UApIekhXMkVhK1dHVEZWWVVxNzFhTVI5QUZuUUtCZ1FERnQ5ekVXK0VzVnVnV2dwNFhaWkNscFhLVHRVak5pRjVmCnBETGIwMWZtZ1VkSnIxa0sxNGs2dmd1TnJ3RTZDbVdPVWNJOCtoK3VlZjQ5RGNpWWhGdHJFMkE2cTNweWFSU3MKdmwzMFlmbXlFSStyZDh1Wm96MSt6dW5DRzhzZi9FTzkrRW9MOFpFWlNoYmxodE4rZWFhM0N4SWh3eS96OWZwRQpLeTNHNVg1emNRS0JnRW8rQnRQUk56M1JBcXM5NXlVK0d3NjRnTktZSktDRFliT2dMZWdENmVnRzVHbWhMYVpaCkRyeFhXc005ODZULzJjdVdPQXdIQ01TSFlNc25oK29ydTRFZzVnRUFiZ2J3bEtqelVMK2svZlB5TmJpYnVoNkMKUEVoU25DWWw1L1d6OGRTRHRuWjJjaEpKMDJpa0NtNlBhZWhIMTRPakdBSytGZ2IwalhYS2JtQlpBb0dBRW0rdApqMFc5L21Od0tzRXRPcU5HMUp0VHpzQWx0THlWaURlSVlvVVhlaS90MU1vYjlHM2FwdmFYbnpPRldzTWpheHptCmpzY0g4ejMrM2ZTT0V1S3NuNVJqOGJTUnExOXZCUmlQTEQyQ2lmOFBWbjdLSmw1WldweXlvVjMwRjl4dStLVFIKU3NIUXRObjZ2cFpPM0VrOXFXM0gyQXdhU1paVEtzNFg2NmIwbnBFQ2dZRUF6RFNjSlp0Mm9zTVpuR1NYdzJkLwpHOFEvN2RBa2I3M2dWOUNYTHUyb0NJMU1raGFFSldjWFFyWGxBOXFVbDRFOXVxNWN2NHhYRHVQc1VXems3ejFmCk1IM01ZR2c2VkZINzBXSmNOeitHNGMrUFlZbTZybXJ6aWhKSE51OFhQYjZKNTlZTUsvdGp4NkEwMEhCenJMWmwKZ3pFTlZiMS84eEl5T2p0NEFBc0RjWTg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
{{ end }}


{{ if .Values.flowmanager.license.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-license
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.license.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.license.localFile | b64enc }}
{{ end }}

{{ if .Values.flowmanager.redis.createSecretFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.flowmanager.redis.fileName | quote }} : |-
    {{ .Files.Get .Values.flowmanager.redis.localFile | b64enc }}
{{ end }}