apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmanager.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "flowmanager.name" . }}
    chart: {{ include "flowmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  FM_GENERAL_ENCRYPTION_KEY: {{ required "A valid FM_GENERAL_ENCRYPTION_KEY is required!" .Values.flowmanager.generalEncryptionKey | b64enc | quote }}
  FM_HTTPS_KEYSTORE_PASSWORD: {{ required "A valid FM_HTTPS_KEYSTORE_PASSWORD is required!" .Values.flowmanager.https.keystorePassword | b64enc | quote }}
  FM_CFT_SHARED_SECRET: {{ required "A valid FM_CFT_SHARED_SECRET is required!" .Values.flowmanager.cftSharedSecret | b64enc | quote }}
  FM_DATABASE_USER_NAME: {{ required "A valid FM_DATABASE_USER_NAME is required!" .Values.flowmanager.db.user | b64enc | quote }}
  FM_DATABASE_USER_PASSWORD: {{ required "A valid FM_DATABASE_USER_PASSWORD is required!" .Values.flowmanager.db.password | b64enc | quote }}
  FM_BUSINESS_CA_PASSWORD: {{ required "A valid FM_BUSINESS_CA_PASSWORD is required!" .Values.flowmanager.business.caPassword | b64enc | quote }}
  FM_GOVERNANCE_CA_PASSWORD: {{ required "A valid FM_GOVERNANCE_CA_PASSWORD is required!" .Values.flowmanager.governance.caPassword | b64enc | quote }}
  {{ if .Values.flowmanager.redis.user }}
  FM_REDIS_USER: {{ .Values.flowmanager.redis.user | b64enc | quote }}
  {{ end }}
  {{ if .Values.flowmanager.redis.password }}
  FM_REDIS_PASSWORD: {{ required "A valid FM_REDIS_PASSWORD is required!" .Values.flowmanager.redis.password | b64enc | quote }}
  {{ end }}
{{ if .Values.extraSecrets }}
  {{ range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{ end }}
{{ end }}