apiVersion: v1
kind: Service
metadata:
  name: {{ template "flowmanager.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "flowmanager.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: {{ include "flowmanager.name" . }}-https
    port: {{ .Values.service.externalPort }}
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ template "flowmanager.name" . }}
    release: {{ .Release.Name | quote }}