version: '3.4'
services:
  flowmanager:
    image: axway/flowmanager:2.0.200903
    hostname: "flowmanager"
    stdin_open: true
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "no"

        #General
        FM_GENERAL_FQDN                              : "flowmanager.example.com"
        FM_GENERAL_UI_PORT                           : "8081"
        FM_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FM_GENERAL_LOGGING_LEVEL                     : "INFO"
        FM_GENERAL_LICENSE                           : "license.xml"
        FM_LOGS_CONSOLE                              : "yes"

        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "true"
        FM_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.p12"
        FM_HTTPS_CERT_ALIAS                          : "ui"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"

        #Mongo
        FM_DATABASE_HOST                             : "fmmongo"
        FM_DATABASE_PORT                             : "27018"
        FM_DATABASE_USER_NAME                        : "storage"
        FM_DATABASE_USER_PASSWORD                    : "storage"
        FM_DATABASE_USE_SSL                          : "false"
        FM_DATABASE_CERTIFICATES                     : "/opt/axway/configs/mongodb.jks"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "governance"
        FM_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.p12"
        FM_GOVERNANCE_CA_PASSWORD                    : "Secret01"

        #JVM
        FM_JVM_XMX                                   : "2G"
        FM_JVM_XMS                                   : "512M"
        FM_JVM_XMN                                   : "768M"
        FM_JVM_DEBUG_ENABLED                         : "false"
        FM_JVM_DEBUG_PORT                            : "8000"
        FM_JVM_DEBUG_SUSPEND                         : "false"
        #FM_JVM_CUSTOM_ARGS                         : ""

    ports:
      - 8081:8081
    depends_on:
      - fmmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license"

  fmmongo:
    build: ./mongo_3.6/
    hostname: fmmongo
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018" # MUST MATCH THE ONE SPECIFIED IN THE FLOWMANAGER ENVIRONMENT VARIABLE
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"