version: '3.4'
services:
  flowmanager:
    image: axway/flowmanager:2.0.20190809
    hostname: "flowmanager"
    stdin_open: true
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "no"

        #General
        FM_GENERAL_FQDN                              : "flowmanager"
        FM_GENERAL_HOSTNAME                          : "flowmanager"
        FM_GENERAL_UI_PORT                           : "8081"
        FM_GENERAL_SAAS_MODE                         : "false"
        FM_GENERAL_HTTP_PORT                         : ""
        FM_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FM_GENERAL_LOGGING_LEVEL                     : "INFO"
        FM_GENERAL_LICENSE                           : "license.xml"
        FM_GENERAL_CUSTOM_LOCATION_PATH              : "/opt/axway/logs"
        FM_LOGS_CONSOLE                              : "yes"

        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "true"
        FM_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.p12"
        FM_HTTPS_CERT_ALIAS                          : "ui"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"
        FM_SESSION_IDLE                              : "900"
        FM_SESSION_EXPIRATION                        : "28800"

        #CFT
        FM_CFT_SHARED_SECRET                         : "Secret01"
        FM_CFT_SFTP_ENABLED                          : "false"
        
        #ST
        FM_ST_WHITELISTING_ENABLED                   : "false"
        FM_ST_WHITELISTING_WATCHDOG_DELAY            : "120"
        
        #Redis
        FM_REDIS_ENABLED                             : "false"
        FM_REDIS_HOSTNAME                            : "redis"
        FM_REDIS_PORT                                : "6379"

        #APIC
        FM_APIC_USE_CATALOG                          : "true"
        FM_APIC_HOST                                 : "https://apicentral.axway.com"
        FM_APIC_CLIENTID                             : "DOSA_XXXXXXXXXXXXXXXXXXXXXXXXXXX"
        FM_APIC_PUBLICKEY                            : "/opt/axway/configs/catalog-public-key.pem"
        FM_APIC_PRIVATEKEY                           : "/opt/axway/configs/catalog-private-key.pem"
        

        #Mongo
        FM_DATABASE_HOST                             : "fmmongo"
        FM_DATABASE_PORT                             : "27018"
        FM_DATABASE_USER_NAME                        : "storage"
        FM_DATABASE_USER_PASSWORD                    : "storage"
        FM_DATABASE_USE_SSL                          : "false"
        FM_DATABASE_CERTIFICATES                     : "/opt/axway/configs/mongodb.jks"
        FM_DISABLE_CHECK_REACHABLE_HOST              : "false"

        #Business
        FM_BUSINESS_CA_CERTIF_ALIAS                  : "business"
        FM_BUSINESS_CA_FILE                          : "/opt/axway/configs/businessca.p12"
        FM_BUSINESS_CA_PASSWORD                      : "Secret01"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "governance"
        FM_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.p12"
        FM_GOVERNANCE_CA_PASSWORD                    : "Secret01"

        #JVM
        FM_JVM_XMX                                   : "2G"
        FM_JVM_XMS                                   : "512M"
        FM_JVM_XMN                                   : "768M"
        FM_JVM_DEBUG_ENABLED                         : "false"
        FM_JVM_DEBUG_PORT                            : "8000"
        FM_JVM_DEBUG_SUSPEND                         : "false"
        #FFM_JVM_CUSTOM_ARGS                          : ""

        #EXTERNAL
        #FM_EXTERNAL_FQDN                            : "flowmanager.example.com"
        #FM_EXTERNAL_UI_PORT                         : "443"

        #Sentinel
        FM_SENTINEL_AUDIT_ENABLED                    : "false"
        FM_SENTINEL_FRONT_END_HOST                   : "localhost"
        FM_SENTINEL_FRONT_END_PORT                   : "1305"
        FM_SENTINEL_FRONT_END_SSL_PORT               : "1303"
        FM_SENTINEL_UI_PORT                          : "1309"
        FM_SENTINEL_USE_CG_CA                        : "true"
    ports:
      - 8081:8081
    depends_on:
      - fmmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license"

  fmmongo:
    build: ./mongo_3.6/
    hostname: fmmongo
    volumes:
       - "mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018" # MUST MATCH THE ONE SPECIFIED IN THE FLOWMANAGER ENVIRONMENT VARIABLE
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"


volumes:
  mongo_data:
