---
apiVersion: v1
kind: Service
metadata:
  name: flowmanager
  labels:
    app: flowmanager
spec:
  ports:
    - name: flowmanager-https
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: "NodePort"
  selector:
    app: flowmanager
